
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shilpi Mazumdar
 */
public class administratorWindow extends javax.swing.JFrame {

    /**
     * Creates new form administratorWindow
     */  
    public administratorWindow() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Passengers = new javax.swing.JMenu();
        searchPassenger = new javax.swing.JMenuItem();
        deletePassenger = new javax.swing.JMenuItem();
        Flights = new javax.swing.JMenu();
        addNewFlights = new javax.swing.JMenuItem();
        generateFlightData = new javax.swing.JMenuItem();
        Administrator = new javax.swing.JMenu();
        deleteadmin = new javax.swing.JMenuItem();
        customerCare = new javax.swing.JMenu();
        raiseComplaint = new javax.swing.JMenuItem();
        contactTerminalHelpDesk = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        Passengers.setText("Passengers");

        searchPassenger.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        searchPassenger.setText("Search Passenger");
        searchPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPassengerActionPerformed(evt);
            }
        });
        Passengers.add(searchPassenger);

        deletePassenger.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deletePassenger.setText("Delete Passenger");
        deletePassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePassengerActionPerformed(evt);
            }
        });
        Passengers.add(deletePassenger);

        jMenuBar1.add(Passengers);

        Flights.setText("Flights");

        addNewFlights.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addNewFlights.setText("Add New Flights");
        addNewFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewFlightsActionPerformed(evt);
            }
        });
        Flights.add(addNewFlights);

        generateFlightData.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        generateFlightData.setText("Generate Flight Data");
        generateFlightData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateFlightDataActionPerformed(evt);
            }
        });
        Flights.add(generateFlightData);

        jMenuBar1.add(Flights);

        Administrator.setText("Administrator");

        deleteadmin.setText("Delete Administrator");
        deleteadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteadminActionPerformed(evt);
            }
        });
        Administrator.add(deleteadmin);

        jMenuBar1.add(Administrator);

        customerCare.setText("Customer Care");

        raiseComplaint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        raiseComplaint.setText("Raise Complaint");
        raiseComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseComplaintActionPerformed(evt);
            }
        });
        customerCare.add(raiseComplaint);

        contactTerminalHelpDesk.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        contactTerminalHelpDesk.setText("Contact Terminal Helpdesk");
        contactTerminalHelpDesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTerminalHelpDeskActionPerformed(evt);
            }
        });
        customerCare.add(contactTerminalHelpDesk);

        jMenuBar1.add(customerCare);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPassengerActionPerformed
        try {
            // To create an object of Search Passenger Window:
            SearchPassenger searchpassenger = new SearchPassenger();
            searchpassenger.setVisible(true);
            desktopPane.add(searchpassenger);
        } catch (SQLException ex) {
            Logger.getLogger(administratorWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchPassengerActionPerformed

    private void addNewFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewFlightsActionPerformed
        // To create an object of Add New Flights Window:
        AddNewFlights addFlights = new AddNewFlights();
        addFlights.setVisible(true);
        desktopPane.add(addFlights);
    }//GEN-LAST:event_addNewFlightsActionPerformed

    private void generateFlightDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateFlightDataActionPerformed
        // To create an object of Generate Flight Data Window:
        GenerateFlightData generateData = new GenerateFlightData();
        generateData.setVisible(true);
        desktopPane.add(generateData);
    }//GEN-LAST:event_generateFlightDataActionPerformed

    private void raiseComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseComplaintActionPerformed
        // To create an object of Raise Complaint Window:
        RaiseComplaint raisecomplaint = new RaiseComplaint();
        raisecomplaint.setVisible(true);
        desktopPane.add(raisecomplaint);
    }//GEN-LAST:event_raiseComplaintActionPerformed

    private void contactTerminalHelpDeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTerminalHelpDeskActionPerformed
        // To create an object of Contact Terminal Helpdesk Window:
        ContactTerminalHelpdesk contactterminalhelpdesk = new ContactTerminalHelpdesk();
        contactterminalhelpdesk.setVisible(true);
        desktopPane.add(contactterminalhelpdesk);
    }//GEN-LAST:event_contactTerminalHelpDeskActionPerformed

    private void deletePassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePassengerActionPerformed
        try {
            // To create an object of Delete Passenger Window:
            DeletePassenger deletepassenger = new DeletePassenger();
            deletepassenger.setVisible(true);
            desktopPane.add(deletepassenger);
        } catch (SQLException ex) {
            Logger.getLogger(administratorWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletePassengerActionPerformed

    private void deleteadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteadminActionPerformed
        try {
            // To create an object of Delete Administrator Window:
            DeleteAdministrator deleteAdmin = new DeleteAdministrator();
            deleteAdmin.setVisible(true);
            desktopPane.add(deleteAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(administratorWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administratorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administratorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administratorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administratorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administratorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administrator;
    private javax.swing.JMenu Flights;
    private javax.swing.JMenu Passengers;
    private javax.swing.JMenuItem addNewFlights;
    private javax.swing.JMenuItem contactTerminalHelpDesk;
    private javax.swing.JMenu customerCare;
    private javax.swing.JMenuItem deletePassenger;
    private javax.swing.JMenuItem deleteadmin;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem generateFlightData;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem raiseComplaint;
    private javax.swing.JMenuItem searchPassenger;
    // End of variables declaration//GEN-END:variables
}
