
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Shilpi Mazumdar
 */
public class ContactTerminalHelpdeskPassenger extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContactTerminalHelpdesk
     */
    
    Connection connection;
    PreparedStatement prestatement;
    
    public ContactTerminalHelpdeskPassenger() {
        initComponents();
        try {
            try {
                // To establish connection with the SQL DB and server (link/stream)
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ContactTerminalHelpdeskPassenger.class.getName()).log(Level.SEVERE, null, ex);
            }
            // To establish connection with database
            connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/airlinemavendatabase", "root", "Lakshmi@06");
        } catch (SQLException ex) {
            Logger.getLogger(ContactTerminalHelpdeskPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner1 = new javax.swing.JLabel();
        banner2 = new javax.swing.JLabel();
        selectcurrentairport = new javax.swing.JLabel();
        currentTerminal = new javax.swing.JLabel();
        D1 = new javax.swing.JRadioButton();
        D2 = new javax.swing.JRadioButton();
        selectairport = new javax.swing.JComboBox<>();
        A1 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        passengerid = new javax.swing.JLabel();
        passengerID = new javax.swing.JTextField();
        getassistance = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(632, 376));
        setMinimumSize(new java.awt.Dimension(632, 376));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        banner1.setForeground(new java.awt.Color(255, 255, 255));
        banner1.setText("You have reached our HelpDesk contact Point");
        getContentPane().add(banner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 17, 382, -1));

        banner2.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        banner2.setForeground(new java.awt.Color(255, 255, 255));
        banner2.setText("Please fill out the below form to help us serve you better !");
        getContentPane().add(banner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 45, 411, -1));

        selectcurrentairport.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        selectcurrentairport.setForeground(new java.awt.Color(255, 255, 255));
        selectcurrentairport.setText("Select current Airport");
        getContentPane().add(selectcurrentairport, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 97, 146, -1));

        currentTerminal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        currentTerminal.setForeground(new java.awt.Color(255, 255, 255));
        currentTerminal.setText("Select current Terminal");
        getContentPane().add(currentTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 136, 146, -1));

        D1.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        D1.setForeground(new java.awt.Color(255, 255, 255));
        D1.setText("Domestic D1");
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 135, 111, -1));

        D2.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        D2.setForeground(new java.awt.Color(255, 255, 255));
        D2.setText("Domestic D2");
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 162, 111, -1));

        selectairport.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        selectairport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "IGI, New Delhi", "T1, New Delhi", "T2, New Delhi", "Kempegowda, Banglore", "Kormangla, Banglore", "Chattrapati Shivaji, Mumbai", "Navi Mumbai, Mumbai", "Dabolim, Goa", "Panjim, Goa", "Heathrow, London", "Gatwick, London", "Oxford, London", "Changi, Singapore", "Chek Lap Kok, Hong Kong", "Incheon International, South Korea", "Daegu International, South Korea", "Vancouver International, Canada", "Calgary International, Canada", "Toronto Pearson International, Canada", "Denver International, US", "Dallas/Fort Worth International, US", "JFK, US", "Paris Charles de Gaulle, France", "Lyon-Saint Exupery, France", "Frankfurt, Germany", "Hamburg, Germany", "Munich International, Germany", "Abu Dhabi International, UAE", "Dubai International, UAE" }));
        getContentPane().add(selectairport, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 95, -1, -1));

        A1.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        A1.setForeground(new java.awt.Color(255, 255, 255));
        A1.setText("International A1");
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 189, 130, -1));

        A3.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        A3.setForeground(new java.awt.Color(255, 255, 255));
        A3.setText("International A3");
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 216, 130, -1));

        passengerid.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        passengerid.setForeground(new java.awt.Color(255, 255, 255));
        passengerid.setText("Passenger ID");
        getContentPane().add(passengerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 245, 146, -1));

        passengerID.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(passengerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 243, 130, -1));

        getassistance.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getassistance.setText("Get Assistance");
        getassistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getassistanceActionPerformed(evt);
            }
        });
        getContentPane().add(getassistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 243, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shilpi Mazumdar\\Desktop\\Acciojob Projects\\Airline Mgmt\\wallpaperflare.com_wallpaper4 (1).jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getassistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getassistanceActionPerformed
        try {
            /* To activate assitance connection by storing passenger details and configuring it to
            send message/call the passenger mobile devices : */
            // To get selected combobox data for current Airport
            String currentairport = selectairport.getSelectedItem().toString();
            String currentterminal = "";
            if(D1.isSelected())
                currentterminal = "Domestic D1";
            else if(D2.isSelected())
                currentterminal = "DOmestic D2";
            else if(A1.isSelected())
                currentterminal = "International A1";
            else if(A3.isSelected())
                currentterminal = "International A3";
            
            String passengeriD = passengerID.getText();
            
            /* To retrieve the contactno of the passenger from the passenger table and 
            automatically storing it into the current window database */
            prestatement = connection.prepareStatement("select * from passengers where idpassengers = ?");
            prestatement.setString(1, passengeriD);
            
            ResultSet res = prestatement.executeQuery();
            res.next();
            
            String contactno = res.getString("contactNo"); 
            
            // Preparing a statement to run a query in SQL
            prestatement = connection.prepareStatement("insert into contactterminalhelpdeskpassenger(idpassenger, currentAirport, currentTerminal, contactNo)values(?,?,?,?)");
            // Set String of every field of contactterminalhelpdeskpassenger table - Similar to the Strings created above
            prestatement.setString(1, passengeriD);
            prestatement.setString(2, currentairport);    
            prestatement.setString(3, currentterminal);
            prestatement.setString(4, contactno);
            
            //Executing the query
            prestatement.executeUpdate();
            
            //Showing a message after successful addition of new passenger data to the passengers table
            JOptionPane.showMessageDialog(null, "Assistance Link Initiated. Please wait for our staff to connect with you !");
            
        } catch (SQLException ex) {
            Logger.getLogger(ContactTerminalHelpdeskPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }//GEN-LAST:event_getassistanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A3;
    private javax.swing.JRadioButton D1;
    private javax.swing.JRadioButton D2;
    private javax.swing.JLabel banner1;
    private javax.swing.JLabel banner2;
    private javax.swing.JLabel currentTerminal;
    private javax.swing.JButton getassistance;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField passengerID;
    private javax.swing.JLabel passengerid;
    private javax.swing.JComboBox<String> selectairport;
    private javax.swing.JLabel selectcurrentairport;
    // End of variables declaration//GEN-END:variables
}
