
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Shilpi Mazumdar
 */
public class ContactTerminalHelpdesk extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContactTerminalHelpdesk
     */
    
    Connection connection;
    PreparedStatement prestatement;
    
    public ContactTerminalHelpdesk() {
        initComponents();
        try {
            try {
                // To establish connection with the SQL DB and server (link/stream)
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ContactTerminalHelpdesk.class.getName()).log(Level.SEVERE, null, ex);
            }
            // To establish connection with database
            connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/airlinemavendatabase", "root", "Lakshmi@06");
        } catch (SQLException ex) {
            Logger.getLogger(ContactTerminalHelpdesk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void sendSMS(String message, String contactNo) throws MalformedURLException, IOException{
            String apiKey = "HsoZ0ihU81bkgDQB9O6Kp3qPCnrwlGyVm7MdevSRu5TYExFjL29kJg4HiuXhBOTbrSZIdyGafEvNQ0KV";
            String senderID = "TXTIND";
            
        try {
            // Encoding the Message
            message = URLEncoder.encode(message,"UTF-8");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(ContactTerminalHelpdesk.class.getName()).log(Level.SEVERE, null, ex);
        }
            String language = "english";
            String route = "p";
            
            // Forming my URL
            String myUrl = "https://www.fast2sms.com/dev/bulkV2?authorization=" + apiKey + "&sender_id=" + senderID + "&message=" + message + "&route=" + route + "v3&numbers=" + contactNo;
            
            //Sending GET Request using JAVA
            URL url = new URL(myUrl);
             
            HttpsURLConnection connect = (HttpsURLConnection)url.openConnection();
            
            connect.getRequestMethod();
            
            connect.setRequestProperty("User-Agent", "International Maven Airlines");
            connect.setRequestProperty("cache-control", "no-cache");
//            int code = connect.getResponseCode();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner1 = new javax.swing.JLabel();
        banner2 = new javax.swing.JLabel();
        selectcurrentairport = new javax.swing.JLabel();
        currentTerminal = new javax.swing.JLabel();
        D1 = new javax.swing.JRadioButton();
        D2 = new javax.swing.JRadioButton();
        selectairport = new javax.swing.JComboBox<>();
        A1 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        AdminID = new javax.swing.JLabel();
        adminID = new javax.swing.JTextField();
        runway = new javax.swing.JRadioButton();
        cargo = new javax.swing.JRadioButton();
        initiatecontact = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(632, 376));
        setMinimumSize(new java.awt.Dimension(632, 376));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        banner1.setForeground(new java.awt.Color(255, 255, 255));
        banner1.setText("You have reached our HelpDesk contact Point");
        getContentPane().add(banner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 17, 382, -1));

        banner2.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        banner2.setForeground(new java.awt.Color(255, 255, 255));
        banner2.setText("Please fill out the below form to help us serve you better !");
        getContentPane().add(banner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 45, 411, -1));

        selectcurrentairport.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        selectcurrentairport.setForeground(new java.awt.Color(255, 255, 255));
        selectcurrentairport.setText("Select Duty Airport");
        getContentPane().add(selectcurrentairport, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 97, 146, -1));

        currentTerminal.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        currentTerminal.setForeground(new java.awt.Color(255, 255, 255));
        currentTerminal.setText("Select current Terminal");
        getContentPane().add(currentTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 136, 146, -1));

        D1.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        D1.setForeground(new java.awt.Color(255, 255, 255));
        D1.setText("Domestic D1");
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 135, 111, -1));

        D2.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        D2.setForeground(new java.awt.Color(255, 255, 255));
        D2.setText("Domestic D2");
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 162, 111, -1));

        selectairport.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        selectairport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "IGI, New Delhi", "T1, New Delhi", "T2, New Delhi", "Kempegowda, Banglore", "Kormangla, Banglore", "Chattrapati Shivaji, Mumbai", "Navi Mumbai, Mumbai", "Dabolim, Goa", "Panjim, Goa", "Heathrow, London", "Gatwick, London", "Oxford, London", "Changi, Singapore", "Chek Lap Kok, Hong Kong", "Incheon International, South Korea", "Daegu International, South Korea", "Vancouver International, Canada", "Calgary International, Canada", "Toronto Pearson International, Canada", "Denver International, US", "Dallas/Fort Worth International, US", "JFK, US", "Paris Charles de Gaulle, France", "Lyon-Saint Exupery, France", "Frankfurt, Germany", "Hamburg, Germany", "Munich International, Germany", "Abu Dhabi International, UAE", "Dubai International, UAE" }));
        getContentPane().add(selectairport, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 95, -1, -1));

        A1.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        A1.setForeground(new java.awt.Color(255, 255, 255));
        A1.setText("International A1");
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 189, 130, -1));

        A3.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        A3.setForeground(new java.awt.Color(255, 255, 255));
        A3.setText("International A3");
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 216, 130, -1));

        AdminID.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        AdminID.setForeground(new java.awt.Color(255, 255, 255));
        AdminID.setText("Admin ID");
        getContentPane().add(AdminID, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 245, 146, -1));

        adminID.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(adminID, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 243, 130, -1));

        runway.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        runway.setForeground(new java.awt.Color(255, 255, 255));
        runway.setText("Service Runway");
        getContentPane().add(runway, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 135, 133, -1));

        cargo.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        cargo.setForeground(new java.awt.Color(255, 255, 255));
        cargo.setText("Cargo Port");
        getContentPane().add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 162, 133, -1));

        initiatecontact.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        initiatecontact.setText("Initiate Contact");
        initiatecontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initiatecontactActionPerformed(evt);
            }
        });
        getContentPane().add(initiatecontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 243, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shilpi Mazumdar\\Desktop\\Acciojob Projects\\Airline Mgmt\\wallpaperflare.com_wallpaper4 (1).jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initiatecontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initiatecontactActionPerformed
        try {
            /* To activate assitance connection by storing passenger details and configuring it to
            send message/call the administrator mobile devices : */
            // To get selected combobox data for current Airport
            String currentairport = selectairport.getSelectedItem().toString();
            String currentterminal = "";
            if(D1.isSelected())
                currentterminal = "Domestic D1";
            else if(D2.isSelected())
                currentterminal = "DOmestic D2";
            else if(A1.isSelected())
                currentterminal = "International A1";
            else if(A3.isSelected())
                currentterminal = "International A3";
            else if(runway.isSelected())
                currentterminal = "Service Runway";
            else if(cargo.isSelected())
                currentterminal = "Cargo Port";
            
            String adminid = adminID.getText();
            
            /* To retrieve the contactno of the passenger from the passenger table and 
            automatically storing it into the current window database */
            // Can I rephrase it into "select idadministrator from administrator" ?
            prestatement = connection.prepareStatement("select * from administrator where idadministrator = ?");
            prestatement.setString(1, adminid);
            
            ResultSet res = prestatement.executeQuery();
            res.next();
            
            /* This is important to store the result of the obtained query into a variable so that we can 
            inject it into the database subsequently */
            String contactno = res.getString("contactNo"); 
            
            // Preparing a statement to run a query in SQL
            prestatement = connection.prepareStatement("insert into contactterminalhelpdesk(idadmin, dutyAirport, currentTerminal, contactNo)values(?,?,?,?)");
            // Set String of every field of administrators table - Similar to the Strings created above
            prestatement.setString(1, adminid);
            prestatement.setString(2, currentairport);
            prestatement.setString(3, currentterminal);
            prestatement.setString(4, contactno);
            
            //Executing the query
            prestatement.executeUpdate();
            
            //Showing a message after successful addition of new passenger data to the passengers table
            JOptionPane.showMessageDialog(null, "Contact Initiated. Please wait for the crew to connect with you !");
            
            String message = "YOUR CONTACT HAS BEEN INITIATED. WE WILL BE CALLING YOU SOON . . .";
            try {
                sendSMS(message,res.getString("contactNo"));
            } catch (IOException ex) {
                Logger.getLogger(ContactTerminalHelpdesk.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ContactTerminalHelpdesk.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_initiatecontactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A3;
    private javax.swing.JLabel AdminID;
    private javax.swing.JRadioButton D1;
    private javax.swing.JRadioButton D2;
    private javax.swing.JTextField adminID;
    private javax.swing.JLabel banner1;
    private javax.swing.JLabel banner2;
    private javax.swing.JRadioButton cargo;
    private javax.swing.JLabel currentTerminal;
    private javax.swing.JButton initiatecontact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton runway;
    private javax.swing.JComboBox<String> selectairport;
    private javax.swing.JLabel selectcurrentairport;
    // End of variables declaration//GEN-END:variables
}
