
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Shilpi Mazumdar
 */
public class DeleteAdministrator extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchPassenger
     */
    Connection connection;
    PreparedStatement prestate;
    public DeleteAdministrator() throws SQLException {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeleteAdministrator.class.getName()).log(Level.SEVERE, null, ex);
        }
        connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/airlinemavendatabase", "root", "Lakshmi@06");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContactNo = new javax.swing.JLabel();
        EmailAddress = new javax.swing.JLabel();
        contactNo = new javax.swing.JTextField();
        PassportNo = new javax.swing.JLabel();
        passportNo = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        CustomerID = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        adminid = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        deleteadminaccount = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();
        FirstName = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        firstName = new javax.swing.JTextField();
        Female = new javax.swing.JRadioButton();
        DateOfBirth = new javax.swing.JLabel();
        profilelevel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchDatabase = new javax.swing.JButton();
        profileLevel = new javax.swing.JComboBox<>();
        terminalDuty = new javax.swing.JLabel();
        dutyterminal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContactNo.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        ContactNo.setForeground(new java.awt.Color(255, 255, 255));
        ContactNo.setText("Contact No");
        getContentPane().add(ContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 97, -1));

        EmailAddress.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        EmailAddress.setForeground(new java.awt.Color(255, 255, 255));
        EmailAddress.setText("E-mail address");
        getContentPane().add(EmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 97, -1));

        contactNo.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(contactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 160, -1));

        PassportNo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        PassportNo.setForeground(new java.awt.Color(255, 255, 255));
        PassportNo.setText("Passport No");
        getContentPane().add(PassportNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 97, -1));

        passportNo.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(passportNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 157, -1));

        LastName.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 97, -1));

        CustomerID.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        CustomerID.setForeground(new java.awt.Color(255, 255, 255));
        CustomerID.setText("Passenger ID");
        getContentPane().add(CustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 112, 26));

        lastName.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 160, -1));

        adminid.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        adminid.setText("Please enter Admin ID");
        getContentPane().add(adminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, -1));

        Gender.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setText("Gender");
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 97, -1));

        deleteadminaccount.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        deleteadminaccount.setText("Delete Admin Account ?");
        deleteadminaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteadminaccountActionPerformed(evt);
            }
        });
        getContentPane().add(deleteadminaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 200, -1));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 157, -1));

        FirstName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name");
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 97, -1));

        Male.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Male.setForeground(new java.awt.Color(255, 255, 255));
        Male.setText("Male");
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        firstName.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 157, -1));

        Female.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Female.setForeground(new java.awt.Color(255, 255, 255));
        Female.setText("Female");
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        DateOfBirth.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        DateOfBirth.setForeground(new java.awt.Color(255, 255, 255));
        DateOfBirth.setText("Date of Birth");
        getContentPane().add(DateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 97, -1));

        profilelevel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        profilelevel.setForeground(new java.awt.Color(255, 255, 255));
        profilelevel.setText("Profile Level");
        getContentPane().add(profilelevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 97, -1));

        email.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 180, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please provide the below details to search the database");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 370, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administrator Database");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 200, -1));

        searchDatabase.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        searchDatabase.setText("Search Database");
        searchDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDatabaseActionPerformed(evt);
            }
        });
        getContentPane().add(searchDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 150, -1));

        profileLevel.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        profileLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Profile", "Executive - D1", "Executive D2", "Executive - A1", "Executive - A3", "Chief Manager - Service Runway", "Assistant Manager - Service Runway", "Chief Manager - Cargo Port", "Assistant Manager - Cargo Port", "Passenger Chief - Departure", "Passenger Chief - Arrival", "General Staff - D1", "General Staff - D2", "General Staff - A1", "General Staff - A3" }));
        getContentPane().add(profileLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 170, -1));

        terminalDuty.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        terminalDuty.setForeground(new java.awt.Color(255, 255, 255));
        terminalDuty.setText("Terminal Duty");
        getContentPane().add(terminalDuty, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 97, -1));

        dutyterminal.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        dutyterminal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Profile", "Executive - D1", "Executive D2", "Executive - A1", "Executive - A3", "Chief Manager - Service Runway", "Assistant Manager - Service Runway", "Chief Manager - Cargo Port", "Assistant Manager - Cargo Port", "Passenger Chief - Departure", "Passenger Chief - Arrival", "General Staff - D1", "General Staff - D2", "General Staff - A1", "General Staff - A3" }));
        getContentPane().add(dutyterminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 170, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shilpi Mazumdar\\Desktop\\Acciojob Projects\\Airline Mgmt\\wallpaperflare.com_wallpaper4 (1).jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDatabaseActionPerformed
        // To autofill passengerID details
        String id = adminid.getText();
        try {
            prestate = connection.prepareStatement("select * from administrator  where idadministrator = ?");
            prestate.setString(1, id);

            ResultSet res = prestate.executeQuery();
            res.next();
            
            firstName.setText(res.getString("firstName"));
            lastName.setText(res.getString("lastName"));
            email.setText(res.getString("email"));
            passportNo.setText(res.getString("passPortNo"));
            contactNo.setText(res.getString("contactNo"));

            // Date Format
            String date = res.getString("dob");
            // Converting string VARCHAR into date
            Date dateformat = null;
            try {
                dateformat = new SimpleDateFormat("dd-mmm-yyyy").parse(date);
            } catch (ParseException ex) {
                Logger.getLogger(SearchPassenger.class.getName()).log(Level.SEVERE, null, ex);
            }
            dob.setDate(dateformat);

            // To set Gender
            String str = res.getString("gender");
            if(str.equals("Male"))
            Male.setSelected(true);
            else if(str.equals("Female"))
            Female.setSelected(true);
            
            profileLevel.setSelectedItem(res.getString("profileLevel"));
            dutyterminal.setSelectedItem(res.getString("terminalDuty"));

        } catch (SQLException ex) {
            Logger.getLogger(DeleteAdministrator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDatabaseActionPerformed

    private void deleteadminaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteadminaccountActionPerformed
        try {
            // To delete entry from the database :
            String passengerID = adminid.getText();
            prestate = connection.prepareStatement("delete from administrator where idadministrator = ?");
            prestate.setString(1, passengerID);
            
            prestate.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Account Deleted Successfully !");
            
        } catch (SQLException ex) {
            Logger.getLogger(DeleteAdministrator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteadminaccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactNo;
    private javax.swing.JLabel CustomerID;
    private javax.swing.JLabel DateOfBirth;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JRadioButton Female;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel LastName;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel PassportNo;
    private javax.swing.JTextField adminid;
    private javax.swing.JTextField contactNo;
    private javax.swing.JButton deleteadminaccount;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JComboBox<String> dutyterminal;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField passportNo;
    private javax.swing.JComboBox<String> profileLevel;
    private javax.swing.JLabel profilelevel;
    private javax.swing.JButton searchDatabase;
    private javax.swing.JLabel terminalDuty;
    // End of variables declaration//GEN-END:variables
}
