
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shilpi Mazumdar
 */
public class PassengerWindow extends javax.swing.JFrame {

    /**
     * Creates new form administratorWindow
     */
    public PassengerWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Passengers = new javax.swing.JMenu();
        deleteExistingPassenger = new javax.swing.JMenuItem();
        Flights = new javax.swing.JMenu();
        bookTickets = new javax.swing.JMenuItem();
        generateTravelHistory = new javax.swing.JMenuItem();
        customerCare = new javax.swing.JMenu();
        submitFeedback = new javax.swing.JMenuItem();
        contactTerminalHelpDesk = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(516, 376));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        Passengers.setText("Passengers");

        deleteExistingPassenger.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        deleteExistingPassenger.setText("Delete Existing Passenger");
        deleteExistingPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteExistingPassengerActionPerformed(evt);
            }
        });
        Passengers.add(deleteExistingPassenger);

        jMenuBar1.add(Passengers);

        Flights.setText("Flights");

        bookTickets.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bookTickets.setText("Book Tickets");
        bookTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketsActionPerformed(evt);
            }
        });
        Flights.add(bookTickets);

        generateTravelHistory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        generateTravelHistory.setText("Generate Travel History");
        generateTravelHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateTravelHistoryActionPerformed(evt);
            }
        });
        Flights.add(generateTravelHistory);

        jMenuBar1.add(Flights);

        customerCare.setText("Customer Care");

        submitFeedback.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        submitFeedback.setText("Submit Feedback");
        submitFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFeedbackActionPerformed(evt);
            }
        });
        customerCare.add(submitFeedback);

        contactTerminalHelpDesk.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        contactTerminalHelpDesk.setText("Contact Terminal Helpdesk");
        contactTerminalHelpDesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTerminalHelpDeskActionPerformed(evt);
            }
        });
        customerCare.add(contactTerminalHelpDesk);

        jMenuBar1.add(customerCare);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketsActionPerformed
        // To create an object of Book Tickets Window:
        BookTickets booktickets = new BookTickets();
        booktickets.setVisible(true);
        desktopPane.add(booktickets);
    }//GEN-LAST:event_bookTicketsActionPerformed

    private void generateTravelHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateTravelHistoryActionPerformed
        // To create an object of Generate Travel History Window:
        GenerateTravelHistory generatetravelhistory = new GenerateTravelHistory();
        generatetravelhistory.setVisible(true);
        desktopPane.add(generatetravelhistory);
    }//GEN-LAST:event_generateTravelHistoryActionPerformed

    private void submitFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFeedbackActionPerformed
        // To create an object of Submit Feedback Window:
        SubmitFeedback submitfeedback = new SubmitFeedback();
        submitfeedback.setVisible(true);
        desktopPane.add(submitfeedback);
    }//GEN-LAST:event_submitFeedbackActionPerformed

    private void contactTerminalHelpDeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTerminalHelpDeskActionPerformed
        // To create an object of Contact Terminal Helpdesk Passenger Window:
        ContactTerminalHelpdeskPassenger contactterminalhelpdeskpassenger = new ContactTerminalHelpdeskPassenger();
        contactterminalhelpdeskpassenger.setVisible(true);
        desktopPane.add(contactterminalhelpdeskpassenger);
    }//GEN-LAST:event_contactTerminalHelpDeskActionPerformed

    private void deleteExistingPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteExistingPassengerActionPerformed
        try {
            // To create an object of Delete Existing Passenger Window:
            DeleteExistingPassenger deleteexistingpassenger = new DeleteExistingPassenger();
            deleteexistingpassenger.setVisible(true);
            desktopPane.add(deleteexistingpassenger);
        } catch (SQLException ex) {
            Logger.getLogger(PassengerWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteExistingPassengerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administratorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administratorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administratorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administratorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Flights;
    private javax.swing.JMenu Passengers;
    private javax.swing.JMenuItem bookTickets;
    private javax.swing.JMenuItem contactTerminalHelpDesk;
    private javax.swing.JMenu customerCare;
    private javax.swing.JMenuItem deleteExistingPassenger;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem generateTravelHistory;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem submitFeedback;
    // End of variables declaration//GEN-END:variables
}
