
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shilpi Mazumdar
 */
public class SignUpPassenger extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPassenger
     */
    
    Connection connection;
    PreparedStatement prestatement;
    
    public SignUpPassenger() {
        initComponents();
        try {
            try {
                // To establish connection with the SQL DB and server (link/stream)
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignUpPassenger.class.getName()).log(Level.SEVERE, null, ex);
            }
            // To establish connection with database
            connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/airlinemavendatabase", "root", "Lakshmi@06");
        } catch (SQLException ex) {
            Logger.getLogger(SignUpPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        passportno = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        Age = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Contactno = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        PassportNo = new javax.swing.JLabel();
        resetdata = new javax.swing.JButton();
        DOB = new javax.swing.JLabel();
        cancelregistration = new javax.swing.JButton();
        FirstName = new javax.swing.JLabel();
        finishregistration = new javax.swing.JButton();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        PassengerID = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();
        address = new javax.swing.JScrollPane();
        addresss = new javax.swing.JTextArea();
        dob = new com.toedter.calendar.JDateChooser();
        password = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        passengerID = new javax.swing.JTextField();
        verify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, -1));

        passportno.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(passportno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 160, -1));

        firstname.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 160, -1));

        Age.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Age.setForeground(new java.awt.Color(255, 255, 255));
        Age.setText("Age");
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 89, -1));

        LastName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 89, -1));

        Password.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 89, -1));

        Contactno.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Contactno.setForeground(new java.awt.Color(255, 255, 255));
        Contactno.setText("Contact No.");
        getContentPane().add(Contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 89, -1));

        Gender.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setText("Gender");
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 89, -1));

        Address.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setText("Address");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 89, -1));

        Email.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email ");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 89, -1));

        PassportNo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        PassportNo.setForeground(new java.awt.Color(255, 255, 255));
        PassportNo.setText("Passport No.");
        getContentPane().add(PassportNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 89, -1));

        resetdata.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        resetdata.setText("Reset Data");
        resetdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetdataActionPerformed(evt);
            }
        });
        getContentPane().add(resetdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 100, -1));

        DOB.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        DOB.setForeground(new java.awt.Color(255, 255, 255));
        DOB.setText("Date of Birth");
        getContentPane().add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 89, -1));

        cancelregistration.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        cancelregistration.setText("Cancel Registration");
        cancelregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelregistrationActionPerformed(evt);
            }
        });
        getContentPane().add(cancelregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 150, -1));

        FirstName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name");
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 89, -1));

        finishregistration.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        finishregistration.setText("Finish Registration");
        finishregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishregistrationActionPerformed(evt);
            }
        });
        getContentPane().add(finishregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 150, -1));

        female.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 90, -1));

        male.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        PassengerID.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        PassengerID.setForeground(new java.awt.Color(255, 255, 255));
        PassengerID.setText("Passenger ID");
        getContentPane().add(PassengerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 89, -1));

        banner.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        banner.setForeground(new java.awt.Color(255, 255, 255));
        banner.setText("New Passenger Registration Portal");
        getContentPane().add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 297, 29));

        addresss.setColumns(20);
        addresss.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        addresss.setRows(5);
        address.setViewportView(addresss);

        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 160, -1));

        password.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        password.setText("Please create a password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 174, -1));

        age.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 50, -1));

        lastname.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 174, -1));

        contactno.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 160, -1));

        passengerID.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(passengerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 160, -1));

        verify.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        verify.setText("verify");
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });
        getContentPane().add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shilpi Mazumdar\\Desktop\\Acciojob Projects\\Airline Mgmt\\wallpaperflare.com_wallpaper4.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetdataActionPerformed
        // To reset data :
        firstname.setText("");
        lastname.setText("");
        email.setText("");
        passportno.setText("");
        addresss.setText("");
        contactno.setText("");
        password.setText("Please create a password");
        age.setText("");
        // To remove radioButton(gender) selection
        male.setSelected(false);
        female.setSelected(false);
        // To remove dateChooser(dob) selection
        dob. setCalendar(null);
    }//GEN-LAST:event_resetdataActionPerformed

    private void cancelregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelregistrationActionPerformed
        // To cancel the registration window
        this.dispose();
    }//GEN-LAST:event_cancelregistrationActionPerformed

    private void finishregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishregistrationActionPerformed
        // Retrieveing data input by the passenger and storing in the passengers table
        String passengerid = passengerID.getText();
        String passworD = password.getText();
        String firstName = firstname.getText();
        String lastName = lastname.getText();

        // Date Format
        Date date = dob.getDate();
        String agE = age.getText();
        String gender = "";
        if(male.isSelected())
        gender = "Male";
        else if(female.isSelected())
        gender = "Female";

        String Passport = passportno.getText();
        String emailaddress = email.getText();
        String addreSS = addresss.getText();
        String contact = contactno.getText();

        // Converting date into a string VARCHAR
        DateFormat dateformat = new SimpleDateFormat("yy-mm-dd");
        String dateofBirth = dateformat.format(date);

        try {
            // Preparing a statement to run a query in SQL
            prestatement = connection.prepareStatement("insert into passengers(idpassengers, firstName, lastName, age, dob, address, passportNo, gender, contactNo, password, email)values(?,?,?,?,?,?,?,?,?,?,?)");
            // Set String of every field of passengers table - Similar to the Strings created above
            prestatement.setString(1, passengerid);
            prestatement.setString(2, firstName);
            prestatement.setString(3, lastName);
            prestatement.setString(4, agE);
            prestatement.setString(5, dateofBirth);
            prestatement.setString(6, addreSS);
            prestatement.setString(7, Passport);
            prestatement.setString(8, gender);
            prestatement.setString(9, contact);
            prestatement.setString(10, passworD);
            prestatement.setString(11, emailaddress);

            //Executing the query
            prestatement.executeUpdate();

            if(male.isSelected() && female.isSelected()){
                //Showing a message to select one option from male and female(gender)
                JOptionPane.showMessageDialog(null, "Please select one Gender Type");
            } else
            //Showing a message after successful addition of new passenger data to the passengers table
            JOptionPane.showMessageDialog(null, "Passenger registration successful !");

        } catch (SQLException ex) {
            Logger.getLogger(SignUpPassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_finishregistrationActionPerformed

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        // To verify the email input by the administrator :
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email.getText())))
        JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
        else
        JOptionPane.showMessageDialog(null, "The email is valid", "Good!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_verifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPassenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPassenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Age;
    private javax.swing.JLabel Contactno;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel PassengerID;
    private javax.swing.JLabel PassportNo;
    private javax.swing.JLabel Password;
    private javax.swing.JScrollPane address;
    private javax.swing.JTextArea addresss;
    private javax.swing.JTextField age;
    private javax.swing.JLabel banner;
    private javax.swing.JButton cancelregistration;
    private javax.swing.JTextField contactno;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton finishregistration;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField passengerID;
    private javax.swing.JTextField passportno;
    private javax.swing.JTextField password;
    private javax.swing.JButton resetdata;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
}
