
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Shilpi Mazumdar
 */
public class SubmitFeedback extends javax.swing.JInternalFrame {

    /**
     * Creates new form RaiseComplaint
     */
    
    Connection connection;
    PreparedStatement prestatement;
    
    public SubmitFeedback() {
        initComponents();
        try {
            try {
                // To establish connection with the SQL DB and server (link/stream)
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SubmitFeedback.class.getName()).log(Level.SEVERE, null, ex);
            }
            // To establish connection with database
            connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/airlinemavendatabase", "root", "Lakshmi@06");
        } catch (SQLException ex) {
            Logger.getLogger(SubmitFeedback.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PassengerID = new javax.swing.JLabel();
        passengerid = new javax.swing.JTextField();
        submitFeedback = new javax.swing.JButton();
        officialGovtID = new javax.swing.JTextField();
        banner1 = new javax.swing.JLabel();
        banner2 = new javax.swing.JLabel();
        Contactno = new javax.swing.JLabel();
        OfficialGovtID = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        descr = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        Rating = new javax.swing.JLabel();
        Appreciated = new javax.swing.JRadioButton();
        Satisfactory = new javax.swing.JRadioButton();
        improvement = new javax.swing.JRadioButton();
        contactno = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(710, 360));
        setMinimumSize(new java.awt.Dimension(710, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PassengerID.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        PassengerID.setForeground(new java.awt.Color(255, 255, 255));
        PassengerID.setText("Passenger ID");
        PassengerID.setPreferredSize(new java.awt.Dimension(68, 17));
        getContentPane().add(PassengerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 80, -1));

        passengerid.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(passengerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 130, -1));

        submitFeedback.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        submitFeedback.setText("Submit Feedback");
        submitFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFeedbackActionPerformed(evt);
            }
        });
        getContentPane().add(submitFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 267, -1, -1));

        officialGovtID.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        officialGovtID.setText("(If Passenger ID not available)");
        getContentPane().add(officialGovtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 210, -1));

        banner1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        banner1.setForeground(new java.awt.Color(255, 255, 255));
        banner1.setText("We value your suggestions as much as we value you");
        getContentPane().add(banner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 430, -1));

        banner2.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        banner2.setForeground(new java.awt.Color(255, 255, 255));
        banner2.setText("Please provide us with your helpful suggestions :) We will expedite to resolve them !");
        getContentPane().add(banner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 44, 575, -1));

        Contactno.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Contactno.setForeground(new java.awt.Color(255, 255, 255));
        Contactno.setText("ContactNo");
        Contactno.setPreferredSize(new java.awt.Dimension(68, 17));
        getContentPane().add(Contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 120, -1));

        OfficialGovtID.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        OfficialGovtID.setForeground(new java.awt.Color(255, 255, 255));
        OfficialGovtID.setText("Official Govt. ID");
        OfficialGovtID.setPreferredSize(new java.awt.Dimension(68, 17));
        getContentPane().add(OfficialGovtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, -1));

        Description.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setText("Description");
        Description.setPreferredSize(new java.awt.Dimension(68, 17));
        getContentPane().add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, -1));

        description.setColumns(20);
        description.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        description.setRows(5);
        descr.setViewportView(description);

        getContentPane().add(descr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        Rating.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Rating.setForeground(new java.awt.Color(255, 255, 255));
        Rating.setText("Rating");
        Rating.setPreferredSize(new java.awt.Dimension(68, 17));
        getContentPane().add(Rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 60, -1));

        Appreciated.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Appreciated.setForeground(new java.awt.Color(255, 255, 255));
        Appreciated.setText("Highly Appreciated");
        getContentPane().add(Appreciated, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 154, 150, -1));

        Satisfactory.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Satisfactory.setForeground(new java.awt.Color(255, 255, 255));
        Satisfactory.setText("Satisfactory Service");
        getContentPane().add(Satisfactory, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 182, 160, -1));

        improvement.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        improvement.setForeground(new java.awt.Color(255, 255, 255));
        improvement.setText("Can Improve in . . .");
        getContentPane().add(improvement, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 209, 170, -1));

        contactno.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 163, -1));

        Name.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Name");
        Name.setPreferredSize(new java.awt.Dimension(68, 17));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, -1));

        name.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 163, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shilpi Mazumdar\\Desktop\\Acciojob Projects\\Airline Mgmt\\wallpaperflare.com_wallpaper4 (1).jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFeedbackActionPerformed
        // To retireve complaint data inputted by the passenger :
        try {
            /* To store the feedback submitted in a separate database that can be accessed 
            by the management : */
            String namE = name.getText();
            String contactNo = contactno.getText();
            String passengerID = passengerid.getText();
            String officialID = officialGovtID.getText();
            String desc = description.getText();
            
            String rating = "";
            if(Appreciated.isSelected())
                rating = "10";
            else if(Satisfactory.isSelected())
                rating = "6";
            else if(improvement.isSelected())
                rating = "3";
            
            String officialgovtid = "";
            if(!passengerID.isEmpty()) {
                /* To retrieve the contactno of the passenger from the passenger table and 
                automatically storing it into the current window database */
                // Can I rephrase it into "select idadministrator from administrator" ?
                prestatement = connection.prepareStatement("select * from passengers where idpassengers = ?");
                prestatement.setString(1, passengerID);

                ResultSet res = prestatement.executeQuery();
                res.next();

                /* This is important to store the result of the obtained query into a variable so that we can 
                inject it into the database subsequently */
                officialID = res.getString("PassportNo"); 
                officialGovtID.setText(officialID);
                officialgovtid = officialID;
            }
            
            // Preparing a statement to run a query in SQL
            prestatement = connection.prepareStatement("insert into submitfeedback(Name, idpassenger, contactNo, officialid, description, rating)values(?,?,?,?,?,?)");
            // Set String of every field of submitfeedback table - Similar to the Strings created above
            prestatement.setString(1, namE);
            prestatement.setString(2, passengerID);
            prestatement.setString(3, contactNo);
            if(!passengerID.isEmpty())
                prestatement.setString(4, officialgovtid);
            else
                prestatement.setString(4, officialID);
            prestatement.setString(5, desc);
            prestatement.setString(6, rating);
            
            //Executing the query
            prestatement.executeUpdate();
            
            //Showing a message after successful addition of new passenger data to the passengers table
            JOptionPane.showMessageDialog(null, "Your Feedback has been submitted ! Thankyou !");
            
        } catch (SQLException ex) {
            Logger.getLogger(RaiseComplaint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitFeedbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Appreciated;
    private javax.swing.JLabel Contactno;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel OfficialGovtID;
    private javax.swing.JLabel PassengerID;
    private javax.swing.JLabel Rating;
    private javax.swing.JRadioButton Satisfactory;
    private javax.swing.JLabel banner1;
    private javax.swing.JLabel banner2;
    private javax.swing.JTextField contactno;
    private javax.swing.JScrollPane descr;
    private javax.swing.JTextArea description;
    private javax.swing.JRadioButton improvement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField officialGovtID;
    private javax.swing.JTextField passengerid;
    private javax.swing.JButton submitFeedback;
    // End of variables declaration//GEN-END:variables
}
